### ISSUE TITLE
[PE-D] I think that `deletetg` should automatically delete students with no tutorial group.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#117]
Since the app is for TA managing student, if student no longer taking that module, it would not be necessary to store them anymore? This assumption is also implicit in `deletetgall` which deletes students that have no tutorial group left. It would be more consistent to allowing deletion in `deletetg` as well instead of having to switch to `delete` to remove that student.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: lawwm/ped#6

**Comment by LowJiaHao99** [comment]
Constitute to a feature change. Will be addressed in future iteration i.e. v1.5
