### ISSUE TITLE
[PE-D] UG mentions command that does not exist

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#119]
![image.png](https://raw.githubusercontent.com/lawwm/ped/main/files/0be46df2-2309-4023-8bf7-0c659b8e192d.png)

`findtgall` is not an actual command. Moreover, sentence does not end with a period.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: lawwm/ped#7

**Comment by vanessaxuuan** [comment]
Same issue as #147
