### ISSUE TITLE
[PE-D] Adding special characters into the email attribute in the json file crashes the app.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W15-3/tp#141]
Step to reproduce the bug:
1. Add some special characters in the email attribute of the json file.

![image.png](https://raw.githubusercontent.com/tandeshao/ped/main/files/66189a30-d2c3-4665-92be-6145d1a7baad.png)

2. Save and close the file.
3. Re-launching the app would delete the original data of tach.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: tandeshao/ped#23

**Comment by vanessaxuuan** [comment]
Related to #142, will be fixed when #142 is fixed
