### ISSUE TITLE
[PE-D] Nonsensical string is able to exit the app.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#143]
Step to reproduce:
1. Type in any nonsensical string after the "exit" string (shown in the image below).
![image.png](https://raw.githubusercontent.com/tandeshao/ped/main/files/ea6934ec-52a5-40e8-8ae7-8849872121af.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: tandeshao/ped#25

**Comment by LowJiaHao99** [comment]
Behavior already specified in user guide
