### ISSUE TITLE
[PE-D] Students should not be allowed to attend 2 tutorials of the same module

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#145]
Steps to reproduce: 

add n/John Doe tg/CS2100 G2 tg/CS2100 G3 e/e0123456@u.nus.edu

Issue: A student cannot enroll in two different tutorials within the same modules

![Screenshot 2022-04-01 at 11.38.07 PM.png](https://raw.githubusercontent.com/jinnhl/ped/main/files/922ce4b8-1643-4fec-a31c-c9368300d85e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jinnhl/ped#7

**Comment by vanessaxuuan** [comment]
It is possible to have multiple tutorial groups from the same module (e.g. LAJ1201 TA7 and LAJ1201 TB15). Since it is a possible scenario, we should not restrict the adding of tutorial groups to one per module only.
