### ISSUE TITLE
[PE-D] GUI is not dynamic.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#94]
The details of a person gets squashed when the window becomes too small. Suggest to limit the minimum size of the window. 

![image.png](https://raw.githubusercontent.com/jltham/ped/main/files/f27b9325-95db-4b6a-92a6-777336826549.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jltham/ped#1

**Comment by LowJiaHao99** [comment]
Same as #132
