### ISSUE TITLE
[PE-D] Adding tutorial group command does not check for the format of tutorial group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#96]
![image.png](https://raw.githubusercontent.com/lawwm/ped/main/files/e34698de-0942-472d-8a0c-de1fc672424a.png)

User is allowed to input any data for the tutorial group.
1. Only module code is checked.
2. Tutorial group code is not checked.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lawwm/ped#1

**Comment by vanessaxuuan** [comment]
#120 and #114 will address this
