### ISSUE TITLE
[PE-D] Never handle multiple spaces between words.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-3/tp#99]
steps to reproduce:
1. type "edit 1 n/boybbbb                    renice" into the command.

Result:

![image.png](https://raw.githubusercontent.com/tandeshao/ped/main/files/d3729da5-8621-417e-a2e6-f80e9f8143b8.png)

I don't recall names having multiple spaces in between. Maybe reduce multiple spaces to a single space when users give arguments that have multiple whitespace between words. 

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: tandeshao/ped#3

**Comment by LowJiaHao99** [comment]
Same as #102
